name: Build KernelSU for Beyond2LTE

on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: 'KernelSU variant to build'
        required: true
        default: 'KernelSU-Next'
        type: choice
        options:
          - 'KernelSU-Next'
          - 'KernelSU'
      kernelsu_tag:
        description: 'KernelSU tag to build'
        required: true
        default: 'next'
        type: string
      susfs_repo:
        description: 'SUSFS repository to use'
        required: true
        default: 'https://gitlab.com/simonpunk/susfs4ksu.git'
        type: choice
        options:
          - 'https://gitlab.com/simonpunk/susfs4ksu.git'
          - 'https://github.com/iHagoss/susfs4ksu.git'
          - 'https://github.com/iHagoss/susfs4ksu-begonia.git'
      device:
        description: 'Device to build for'
        required: true
        default: 'beyond2lte'
        type: choice
        options:
          - 'beyond2lte'
          - 'beyond1lte'
          - 'beyond0lte'
          - 'beyondx'
          - 'beyondxq'
          - 'beyond0q'
          - 'beyond1q'
          - 'beyond2q'

env:
  GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
  ARCH: arm64
  SUBARCH: arm64
  DEVICE: ${{ inputs.device }}
  DEFCONFIG: ${{ inputs.device }}_defconfig
  KERNEL_NAME: ExtremeKRNL-Nexus-KernelSU
  CLANG_VERSION: "18.0.0"
  BUILD_USER: iHagoss
  BUILD_HOST: github-actions

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PUSH_TOKEN }}
        fetch-depth: 0
        submodules: recursive

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          git \
          wget \
          curl \
          zip \
          unzip \
          python3 \
          python3-pip \
          ccache \
          clang \
          lld \
          llvm \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabihf

    - name: Setup ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ env.DEVICE }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ env.DEVICE }}-

    - name: Configure ccache
      run: |
        ccache --set-config=max_size=2G
        ccache --set-config=compression=true
        ccache --zero-stats

    - name: Setup toolchain symlinks
      run: |
        sudo mkdir -p /usr/local/bin
        
        # Create Android-specific symlinks for aarch64
        sudo ln -sf /usr/bin/aarch64-linux-gnu-gcc /usr/local/bin/aarch64-linux-android-gcc
        sudo ln -sf /usr/bin/aarch64-linux-gnu-g++ /usr/local/bin/aarch64-linux-android-g++
        sudo ln -sf /usr/bin/aarch64-linux-gnu-ar /usr/local/bin/aarch64-linux-android-ar
        sudo ln -sf /usr/bin/aarch64-linux-gnu-as /usr/local/bin/aarch64-linux-android-as
        sudo ln -sf /usr/bin/aarch64-linux-gnu-ld /usr/local/bin/aarch64-linux-android-ld
        sudo ln -sf /usr/bin/aarch64-linux-gnu-strip /usr/local/bin/aarch64-linux-android-strip
        sudo ln -sf /usr/bin/aarch64-linux-gnu-objcopy /usr/local/bin/aarch64-linux-android-objcopy
        sudo ln -sf /usr/bin/aarch64-linux-gnu-objdump /usr/local/bin/aarch64-linux-android-objdump
        sudo ln -sf /usr/bin/aarch64-linux-gnu-nm /usr/local/bin/aarch64-linux-android-nm
        sudo ln -sf /usr/bin/aarch64-linux-gnu-ranlib /usr/local/bin/aarch64-linux-android-ranlib
        
        # Create Android-specific symlinks for arm
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-gcc /usr/local/bin/arm-linux-androideabi-gcc
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-g++ /usr/local/bin/arm-linux-androideabi-g++
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-ar /usr/local/bin/arm-linux-androideabi-ar
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-as /usr/local/bin/arm-linux-androideabi-as
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-ld /usr/local/bin/arm-linux-androideabi-ld
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-strip /usr/local/bin/arm-linux-androideabi-strip
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-objcopy /usr/local/bin/arm-linux-androideabi-objcopy
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-objdump /usr/local/bin/arm-linux-androideabi-objdump
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-nm /usr/local/bin/arm-linux-androideabi-nm
        sudo ln -sf /usr/bin/arm-linux-gnueabihf-ranlib /usr/local/bin/arm-linux-androideabi-ranlib
        
        # Verify toolchain setup
        echo "✅ Toolchain setup complete!"
        echo "Clang version:"
        clang --version
        echo "GCC aarch64 version:"
        aarch64-linux-android-gcc --version
        echo "GCC arm version:"
        arm-linux-androideabi-gcc --version

    - name: Clone KernelSU
      run: |
        echo "Cloning KernelSU variant: ${{ inputs.kernelsu_variant }}"
        echo "Using tag: ${{ inputs.kernelsu_tag }}"
        
        if [ "${{ inputs.kernelsu_variant }}" == "KernelSU-Next" ]; then
          git clone --depth=1 --branch ${{ inputs.kernelsu_tag }} https://github.com/KernelSU-Next/KernelSU-Next.git KernelSU
        else
          git clone --depth=1 --branch ${{ inputs.kernelsu_tag }} https://github.com/tiann/KernelSU.git KernelSU
        fi
        
        # Debug: Check what was cloned
        echo "KernelSU directory contents:"
        ls -la KernelSU/
        if [ -d "KernelSU/kernel" ]; then
          echo "KernelSU/kernel directory contents:"
          ls -la KernelSU/kernel/
        fi

    - name: Clone SUSFS
      run: |
        echo "Cloning SUSFS from: ${{ inputs.susfs_repo }}"
        git clone --depth=1 ${{ inputs.susfs_repo }} susfs
        
        # Debug: Check what was cloned
        echo "SUSFS directory contents:"
        ls -la susfs/
        if [ -d "susfs/kernel_patches" ]; then
          echo "SUSFS kernel_patches directory contents:"
          ls -la susfs/kernel_patches/
        fi

    - name: Integrate KernelSU
      run: |
        echo "Integrating KernelSU..."
        
        # Check if KernelSU directory exists and has content
        if [ ! -d "KernelSU" ]; then
          echo "❌ KernelSU directory not found!"
          exit 1
        fi
        
        # Find KernelSU kernel files - they might be in different locations
        if [ -d "KernelSU/kernel" ]; then
          echo "✅ Found KernelSU kernel directory"
          # Copy KernelSU kernel files
          cp -r KernelSU/kernel/* ./
          KERNELSU_PATH="KernelSU/kernel"
        elif [ -d "KernelSU/ksu" ]; then
          echo "✅ Found KernelSU ksu directory"
          # Some versions might have files in ksu directory
          cp -r KernelSU/ksu/* ./
          KERNELSU_PATH="KernelSU/ksu"
        else
          echo "❌ KernelSU kernel files not found in expected locations"
          echo "Available directories in KernelSU:"
          find KernelSU -type d -maxdepth 2
          exit 1
        fi
        
        # Backup original fs/exec.c if it exists
        if [ -f fs/exec.c ]; then
          cp fs/exec.c fs/exec.c.backup
          echo "✅ Backed up original fs/exec.c"
        fi
        
        # Run KernelSU setup script if it exists
        if [ -f "$KERNELSU_PATH/setup.sh" ]; then
          echo "✅ Found KernelSU setup script, running it..."
          chmod +x "$KERNELSU_PATH/setup.sh"
          bash "$KERNELSU_PATH/setup.sh"
        else
          echo "⚠️  KernelSU setup script not found, manual integration may be needed"
        fi
        
        # Verify KernelSU integration
        if [ -f "ksu.c" ] || [ -f "kernel/ksu.c" ] || [ -d "KernelSU" ]; then
          echo "✅ KernelSU integration appears successful"
        else
          echo "⚠️  KernelSU integration verification failed"
        fi

    - name: Integrate SUSFS
      run: |
        echo "Integrating SUSFS..."
        
        # Check if SUSFS directory exists
        if [ ! -d "susfs" ]; then
          echo "❌ SUSFS directory not found!"
          exit 1
        fi
        
        # Try different SUSFS integration methods
        SUSFS_INTEGRATED=false
        
        # Method 1: Look for kernel_patches directory
        if [ -d "susfs/kernel_patches" ]; then
          echo "✅ Found SUSFS kernel_patches directory"
          cp -r susfs/kernel_patches/* ./
          SUSFS_INTEGRATED=true
        fi
        
        # Method 2: Look for direct kernel files
        if [ -d "susfs/kernel" ]; then
          echo "✅ Found SUSFS kernel directory"
          cp -r susfs/kernel/* ./
          SUSFS_INTEGRATED=true
        fi
        
        # Method 3: Look for setup script in different locations
        for setup_script in "susfs/setup.sh" "susfs/kernel_patches/setup.sh" "susfs/kernel/setup.sh"; do
          if [ -f "$setup_script" ]; then
            echo "✅ Found SUSFS setup script: $setup_script"
            chmod +x "$setup_script"
            bash "$setup_script"
            SUSFS_INTEGRATED=true
            break
          fi
        done
        
        if [ "$SUSFS_INTEGRATED" = false ]; then
          echo "⚠️  SUSFS integration method not found, but continuing..."
          echo "Available directories in susfs:"
          find susfs -type d -maxdepth 2
        else
          echo "✅ SUSFS integration completed"
        fi

    - name: Find and prepare defconfig
      run: |
        echo "Searching for defconfig files..."
        
        # Search for defconfig files
        echo "Available defconfig files:"
        find arch/arm64/configs -name "*${{ inputs.device }}*" -o -name "*beyond*" -o -name "*exynos9820*" | head -10
        
        # Try different defconfig names in order of preference
        DEFCONFIG_FOUND=false
        for config in ${{ inputs.device }}_defconfig ${DEVICE}_defconfig beyond2lte_defconfig beyond_defconfig exynos9820-beyond2lte_defconfig exynos9820_defconfig; do
          if [ -f "arch/arm64/configs/$config" ]; then
            echo "✅ Found defconfig: $config"
            echo "DEFCONFIG=$config" >> $GITHUB_ENV
            DEFCONFIG_FOUND=true
            break
          fi
        done
        
        # Fallback to any defconfig with device name in it
        if [ "$DEFCONFIG_FOUND" = false ]; then
          FOUND_CONFIG=$(find arch/arm64/configs -name "*${{ inputs.device }}*" | head -1)
          if [ -n "$FOUND_CONFIG" ]; then
            DEFCONFIG=$(basename "$FOUND_CONFIG")
            echo "✅ Using fallback defconfig: $DEFCONFIG"
            echo "DEFCONFIG=$DEFCONFIG" >> $GITHUB_ENV
            DEFCONFIG_FOUND=true
          else
            # Last resort - try beyond configs
            FOUND_CONFIG=$(find arch/arm64/configs -name "*beyond*" | head -1)
            if [ -n "$FOUND_CONFIG" ]; then
              DEFCONFIG=$(basename "$FOUND_CONFIG")
              echo "✅ Using beyond fallback defconfig: $DEFCONFIG"
              echo "DEFCONFIG=$DEFCONFIG" >> $GITHUB_ENV
              DEFCONFIG_FOUND=true
            fi
          fi
        fi
        
        if [ "$DEFCONFIG_FOUND" = false ]; then
          echo "❌ No suitable defconfig found!"
          echo "Available defconfigs in arch/arm64/configs:"
          ls -la arch/arm64/configs/ | grep -E "(beyond|exynos|${{ inputs.device }})"
          exit 1
        fi

    - name: Configure kernel
      run: |
        echo "Configuring kernel with defconfig: $DEFCONFIG"
        
        # Ensure we have a Makefile for clean
        if [ ! -f Makefile ]; then
          echo "❌ No Makefile found!"
          ls -la
          exit 1
        fi
        
        # Clean previous builds if targets exist
        if make -n clean >/dev/null 2>&1; then
          make clean
        fi
        if make -n mrproper >/dev/null 2>&1; then
          make mrproper
        fi
        
        # Configure with defconfig
        make CC=clang ARCH=$ARCH SUBARCH=$SUBARCH CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- $DEFCONFIG
        
        # Enable KernelSU
        echo "CONFIG_KSU=y" >> .config
        echo "CONFIG_KSU_DEBUG=n" >> .config
        
        # Enable SUSFS if available
        if grep -q "CONFIG_KSU_SUSFS" arch/arm64/configs/$DEFCONFIG 2>/dev/null; then
          echo "✅ Enabling SUSFS support"
          echo "CONFIG_KSU_SUSFS=y" >> .config
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> .config
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> .config
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> .config
        else
          echo "⚠️  SUSFS config options not found in defconfig"
        fi
        
        # Regenerate config
        make CC=clang ARCH=$ARCH SUBARCH=$SUBARCH CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- olddefconfig
        
        # Verify KernelSU is enabled
        if grep -q "CONFIG_KSU=y" .config; then
          echo "✅ KernelSU enabled in config"
        else
          echo "⚠️  KernelSU not found in final config"
        fi

    - name: Build kernel
      run: |
        echo "Starting kernel build..."
        
        # Start build with verbose output
        make -j$(nproc) \
          CC=clang \
          ARCH=$ARCH \
          SUBARCH=$SUBARCH \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi- \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CONFIG_NO_ERROR_ON_MISMATCH=y \
          V=1 \
          2>&1 | tee build.log

    - name: Check build result
      run: |
        if [ -f arch/arm64/boot/Image ]; then
          echo "✅ Kernel built successfully!"
          echo "Kernel image details:"
          ls -la arch/arm64/boot/
          file arch/arm64/boot/Image
        else
          echo "❌ Kernel build failed!"
          echo "Build directory contents:"
          ls -la arch/arm64/boot/ || echo "Boot directory not found"
          echo ""
          echo "Last 100 lines of build log:"
          tail -100 build.log
          echo ""
          echo "Error summary:"
          grep -i error build.log | tail -20
          exit 1
        fi

    - name: Prepare kernel image
      run: |
        mkdir -p output
        
        # Copy kernel image
        cp arch/arm64/boot/Image output/
        
        # Create kernel zip name with timestamp
        TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
        KERNEL_ZIP="$KERNEL_NAME-$DEVICE-${{ inputs.kernelsu_variant }}-$TIMESTAMP.zip"
        echo "KERNEL_ZIP=$KERNEL_ZIP" >> $GITHUB_ENV
        
        # Get kernel version
        KERNEL_VERSION=$(cat include/config/kernel.release 2>/dev/null || echo "unknown")
        echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
        
        # Create info file
        cat > output/build_info.txt << EOF
        Kernel: $KERNEL_NAME
        Device: $DEVICE
        Version: $KERNEL_VERSION
        KernelSU: ${{ inputs.kernelsu_variant }} (${{ inputs.kernelsu_tag }})
        SUSFS: ${{ inputs.susfs_repo }}
        Built: $(date)
        Builder: $BUILD_USER
        Commit: $GITHUB_SHA
        EOF
        
        echo "✅ Kernel preparation completed"

    - name: Create flashable zip
      run: |
        cd output
        
        # Create AnyKernel3 structure
        mkdir -p anykernel3
        cd anykernel3
        
        # Download AnyKernel3
        echo "Downloading AnyKernel3..."
        wget -q https://github.com/osm0sis/AnyKernel3/archive/refs/heads/master.zip
        unzip -q master.zip
        cp -r AnyKernel3-master/* .
        rm -rf AnyKernel3-master master.zip
        
        # Configure AnyKernel3 for selected device
        cat > anykernel.sh << 'EOF'
        # AnyKernel3 Ramdisk Mod Script
        # osm0sis @ xda-developers
        
        ## AnyKernel setup
        # begin properties
        properties() { '
        kernel.string=ExtremeKRNL-Nexus-KernelSU
        do.devicecheck=1
        do.modules=0
        do.systemless=1
        do.cleanup=1
        do.cleanuponabort=0
        device.name1=${{ inputs.device }}
        device.name2=beyond2lte
        device.name3=SM-G975F
        device.name4=beyond1lte
        device.name5=SM-G973F
        supported.versions=9-14
        supported.patchlevels=
        '; } # end properties
        
        # shell variables
        block=/dev/block/platform/13d60000.ufs/by-name/boot;
        is_slot_device=0;
        ramdisk_compression=auto;
        
        ## AnyKernel methods (DO NOT CHANGE)
        # import patching functions/variables - see for reference
        . tools/ak3-core.sh;
        
        ## AnyKernel file attributes
        # set permissions/ownership for included ramdisk files
        set_perm_recursive 0 0 755 644 $ramdisk/*;
        set_perm_recursive 0 0 750 750 $ramdisk/init* $ramdisk/sbin;
        
        ## AnyKernel boot install
        dump_boot;
        write_boot;
        EOF
        
        # Copy kernel image
        cp ../Image .
        
        # Create zip
        zip -r ../$KERNEL_ZIP * -x "*.git*" "*.md" "*.txt"
        
        cd ..
        echo "✅ Flashable zip created: $KERNEL_ZIP"
        ls -la $KERNEL_ZIP

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_ZIP }}
        path: |
          output/${{ env.KERNEL_ZIP }}
          output/build_info.txt
          build.log

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: ${{ env.KERNEL_VERSION }}-${{ github.run_number }}
        name: ${{ env.KERNEL_NAME }} - ${{ env.KERNEL_VERSION }}
        body: |
          ## KernelSU Build for ${{ inputs.device }}
          
          **Device:** ${{ env.DEVICE }}
          **Kernel Version:** ${{ env.KERNEL_VERSION }}
          **KernelSU:** ${{ inputs.kernelsu_variant }} (${{ inputs.kernelsu_tag }})
          **SUSFS:** ${{ inputs.susfs_repo }}
          **Built:** $(date)
          
          ### Installation
          1. Boot into custom TWRP (Extreme's version)
          2. Flash the kernel zip
          3. Reboot
          4. Install KernelSU manager app
          
          ### Features
          - KernelSU integrated
          - SUSFS support
          - Optimized for Extreme ROM NEXUS
          - Self-healing build system
          
        files: |
          output/${{ env.KERNEL_ZIP }}
          output/build_info.txt
        token: ${{ secrets.GH_PUSH_TOKEN }}

    - name: Build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Status:** ✅ Success" >> $GITHUB_STEP_SUMMARY
        echo "- **Kernel:** $KERNEL_NAME" >> $GITHUB_STEP_SUMMARY
        echo "- **Device:** $DEVICE" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** $KERNEL_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "- **KernelSU:** ${{ inputs.kernelsu_variant }} (${{ inputs.kernelsu_tag }})" >> $GITHUB_STEP_SUMMARY
        echo "- **SUSFS:** ${{ inputs.susfs_repo }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Output:** $KERNEL_ZIP" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ccache stats" >> $GITHUB_STEP_SUMMARY
        ccache --show-stats >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ccache stats" >> $GITHUB_STEP_SUMMARY
        ccache --show-stats >> $GITHUB_STEP_SUMMARY
