# Complete KernelSU Build Guide for Beyond2LTE (Exynos 9820)

# ✅ Device: Beyond2LTE (NOT 5G) - Exynos 9820
# ✅ Samsung Galaxy s10+ (G975f)
# ✅ Target ROM: Extreme Nexus ROM

name: Build KernelSU for Beyond2LTE

on:
  workflow_dispatch:
    inputs:
      kernelsu_tag:
        description: 'KernelSU tag to build'
        required: true
        default: 'main'
        type: string
      susfs_repo:
        description: 'SUSFS repository to use'
        required: true
        default: 'https://github.com/iHagoss/susfs4ksu.git'
        type: choice
        options:
          - 'https://github.com/iHagoss/susfs4ksu.git'
          - 'https://github.com/iHagoss/susfs4ksu-begonia.git'
          - 'https://github.com/simonpunk/susfs4ksu.git'

env:
  GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
  ARCH: arm64
  SUBARCH: arm64
  DEVICE: beyond2lte
  DEFCONFIG: beyond2lte_defconfig
  KERNEL_NAME: ExtremeKRNL-Nexus-KernelSU
  CLANG_VERSION: "18.0.0"
  BUILD_USER: iHagoss
  BUILD_HOST: github-actions

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PUSH_TOKEN }}
        fetch-depth: 0
        submodules: recursive

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          git \
          wget \
          curl \
          zip \
          unzip \
          python3 \
          python3-pip \
          ccache \
          clang \
          lld \
          llvm

    - name: Setup ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ env.DEVICE }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ env.DEVICE }}-

    - name: Configure ccache
      run: |
        ccache --set-config=max_size=2G
        ccache --set-config=compression=true
        ccache --zero-stats

    - name: Download and setup Clang toolchain
      run: |
        mkdir -p ~/toolchain
        cd ~/toolchain
        
        # Download AOSP Clang (more reliable)
        echo "Downloading Clang toolchain..."
        wget -q --timeout=30 --tries=3 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r487747c.tar.gz -O clang.tar.gz
        
        if [ ! -f clang.tar.gz ]; then
          echo "Primary clang download failed, trying alternative..."
          wget -q --timeout=30 --tries=3 https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz -O clang.tar.xz
          mkdir clang
          tar -xf clang.tar.xz --strip-components=1 -C clang
        else
          mkdir clang
          tar -xzf clang.tar.gz -C clang
        fi
        
        # Download GCC cross compilers from reliable mirror
        echo "Downloading GCC aarch64 toolchain..."
        wget -q --timeout=30 --tries=3 https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz -O gcc-aarch64.tar.xz
        
        if [ ! -f gcc-aarch64.tar.xz ]; then
          echo "Linaro download failed, using system gcc..."
          sudo apt-get install -y gcc-aarch64-linux-gnu
          mkdir -p gcc-aarch64/bin
          ln -s /usr/bin/aarch64-linux-gnu-gcc gcc-aarch64/bin/aarch64-linux-android-gcc
          ln -s /usr/bin/aarch64-linux-gnu-g++ gcc-aarch64/bin/aarch64-linux-android-g++
          ln -s /usr/bin/aarch64-linux-gnu-ar gcc-aarch64/bin/aarch64-linux-android-ar
          ln -s /usr/bin/aarch64-linux-gnu-as gcc-aarch64/bin/aarch64-linux-android-as
          ln -s /usr/bin/aarch64-linux-gnu-ld gcc-aarch64/bin/aarch64-linux-android-ld
          ln -s /usr/bin/aarch64-linux-gnu-strip gcc-aarch64/bin/aarch64-linux-android-strip
          ln -s /usr/bin/aarch64-linux-gnu-objcopy gcc-aarch64/bin/aarch64-linux-android-objcopy
          ln -s /usr/bin/aarch64-linux-gnu-objdump gcc-aarch64/bin/aarch64-linux-android-objdump
          ln -s /usr/bin/aarch64-linux-gnu-nm gcc-aarch64/bin/aarch64-linux-android-nm
          ln -s /usr/bin/aarch64-linux-gnu-ranlib gcc-aarch64/bin/aarch64-linux-android-ranlib
        else
          mkdir gcc-aarch64
          tar -xf gcc-aarch64.tar.xz --strip-components=1 -C gcc-aarch64
          # Create android-specific symlinks
          cd gcc-aarch64/bin
          for tool in gcc g++ ar as ld strip objcopy objdump nm ranlib; do
            if [ -f "aarch64-linux-gnu-$tool" ]; then
              ln -sf "aarch64-linux-gnu-$tool" "aarch64-linux-android-$tool"
            fi
          done
          cd ~/toolchain
        fi
        
        # Download ARM32 GCC
        echo "Downloading GCC arm toolchain..."
        wget -q --timeout=30 --tries=3 https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz -O gcc-arm.tar.xz
        
        if [ ! -f gcc-arm.tar.xz ]; then
          echo "Linaro ARM download failed, using system gcc..."
          sudo apt-get install -y gcc-arm-linux-gnueabihf
          mkdir -p gcc-arm/bin
          ln -s /usr/bin/arm-linux-gnueabihf-gcc gcc-arm/bin/arm-linux-androideabi-gcc
          ln -s /usr/bin/arm-linux-gnueabihf-g++ gcc-arm/bin/arm-linux-androideabi-g++
          ln -s /usr/bin/arm-linux-gnueabihf-ar gcc-arm/bin/arm-linux-androideabi-ar
          ln -s /usr/bin/arm-linux-gnueabihf-as gcc-arm/bin/arm-linux-androideabi-as
          ln -s /usr/bin/arm-linux-gnueabihf-ld gcc-arm/bin/arm-linux-androideabi-ld
          ln -s /usr/bin/arm-linux-gnueabihf-strip gcc-arm/bin/arm-linux-androideabi-strip
          ln -s /usr/bin/arm-linux-gnueabihf-objcopy gcc-arm/bin/arm-linux-androideabi-objcopy
          ln -s /usr/bin/arm-linux-gnueabihf-objdump gcc-arm/bin/arm-linux-androideabi-objdump
          ln -s /usr/bin/arm-linux-gnueabihf-nm gcc-arm/bin/arm-linux-androideabi-nm
          ln -s /usr/bin/arm-linux-gnueabihf-ranlib gcc-arm/bin/arm-linux-androideabi-ranlib
        else
          mkdir gcc-arm
          tar -xf gcc-arm.tar.xz --strip-components=1 -C gcc-arm
          # Create android-specific symlinks
          cd gcc-arm/bin
          for tool in gcc g++ ar as ld strip objcopy objdump nm ranlib; do
            if [ -f "arm-linux-gnueabihf-$tool" ]; then
              ln -sf "arm-linux-gnueabihf-$tool" "arm-linux-androideabi-$tool"
            fi
          done
          cd ~/toolchain
        fi
        
        # Verify toolchain
        echo "Verifying toolchain setup..."
        ls -la ~/toolchain/
        
        # Make sure clang exists
        if [ -f ~/toolchain/clang/bin/clang ]; then
          echo "✅ Clang found"
          ~/toolchain/clang/bin/clang --version
        else
          echo "❌ Clang not found, using system clang"
          which clang
        fi
        
        # Check GCC
        if [ -f ~/toolchain/gcc-aarch64/bin/aarch64-linux-android-gcc ]; then
          echo "✅ GCC aarch64 found"
          ~/toolchain/gcc-aarch64/bin/aarch64-linux-android-gcc --version
        else
          echo "❌ GCC aarch64 not found"
        fi
        
        if [ -f ~/toolchain/gcc-arm/bin/arm-linux-androideabi-gcc ]; then
          echo "✅ GCC arm found"
          ~/toolchain/gcc-arm/bin/arm-linux-androideabi-gcc --version
        else
          echo "❌ GCC arm not found"
        fi

    - name: Setup PATH
      run: |
        # Add toolchain to PATH with fallbacks
        if [ -d ~/toolchain/clang/bin ]; then
          echo "$HOME/toolchain/clang/bin" >> $GITHUB_PATH
        fi
        if [ -d ~/toolchain/gcc-aarch64/bin ]; then
          echo "$HOME/toolchain/gcc-aarch64/bin" >> $GITHUB_PATH
        fi
        if [ -d ~/toolchain/gcc-arm/bin ]; then
          echo "$HOME/toolchain/gcc-arm/bin" >> $GITHUB_PATH
        fi
        
        # Verify PATH setup
        echo "Current PATH:"
        echo $PATH
        
        # Test compilers
        echo "Testing compilers..."
        which clang || echo "clang not in PATH"
        which aarch64-linux-android-gcc || echo "aarch64-linux-android-gcc not in PATH"
        which arm-linux-androideabi-gcc || echo "arm-linux-androideabi-gcc not in PATH"

    - name: Clone KernelSU
      run: |
        git clone --depth=1 --branch ${{ inputs.kernelsu_tag }} https://github.com/tiann/KernelSU.git KernelSU
        echo "KernelSU cloned successfully"

    - name: Clone SUSFS
      run: |
        git clone --depth=1 ${{ inputs.susfs_repo }} susfs
        echo "SUSFS cloned successfully"

    - name: Integrate KernelSU
      run: |
        # Copy KernelSU to kernel directory
        cp -r KernelSU/kernel/* ./
        
        # Find and backup original fs/exec.c
        if [ -f fs/exec.c ]; then
          cp fs/exec.c fs/exec.c.backup
        fi
        
        # Apply KernelSU patches
        if [ -f KernelSU/kernel/setup.sh ]; then
          chmod +x KernelSU/kernel/setup.sh
          bash KernelSU/kernel/setup.sh
        fi

    - name: Integrate SUSFS
      run: |
        # Copy SUSFS files
        if [ -d susfs/kernel_patches ]; then
          cp -r susfs/kernel_patches/* ./
        fi
        
        # Apply SUSFS patches if present
        if [ -f susfs/kernel_patches/KernelSU/kernel/setup.sh ]; then
          chmod +x susfs/kernel_patches/KernelSU/kernel/setup.sh
          bash susfs/kernel_patches/KernelSU/kernel/setup.sh
        fi

    - name: Find and prepare defconfig
      run: |
        # Search for defconfig files
        find arch/arm64/configs -name "*beyond2lte*" -o -name "*beyond*" -o -name "*exynos9820*" | head -5
        
        # Try different defconfig names
        for config in beyond2lte_defconfig beyond_defconfig exynos9820-beyond2lte_defconfig; do
          if [ -f "arch/arm64/configs/$config" ]; then
            echo "Found defconfig: $config"
            echo "DEFCONFIG=$config" >> $GITHUB_ENV
            break
          fi
        done
        
        # Fallback to any defconfig with beyond in the name
        if [ -z "$DEFCONFIG" ]; then
          FOUND_CONFIG=$(find arch/arm64/configs -name "*beyond*" | head -1)
          if [ -n "$FOUND_CONFIG" ]; then
            DEFCONFIG=$(basename "$FOUND_CONFIG")
            echo "Using fallback defconfig: $DEFCONFIG"
            echo "DEFCONFIG=$DEFCONFIG" >> $GITHUB_ENV
          fi
        fi

    - name: Configure kernel
      run: |
        # Clean previous builds
        make clean
        make mrproper
        
        # Configure with defconfig
        make CC=clang ARCH=$ARCH SUBARCH=$SUBARCH CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- $DEFCONFIG
        
        # Enable KernelSU
        echo "CONFIG_KSU=y" >> .config
        echo "CONFIG_KSU_DEBUG=n" >> .config
        
        # Enable SUSFS if available
        if grep -q "CONFIG_KSU_SUSFS" arch/arm64/configs/$DEFCONFIG 2>/dev/null; then
          echo "CONFIG_KSU_SUSFS=y" >> .config
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> .config
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> .config
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> .config
        fi
        
        # Regenerate config
        make CC=clang ARCH=$ARCH SUBARCH=$SUBARCH CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- olddefconfig

    - name: Build kernel
      run: |
        # Start build
        make -j$(nproc) \
          CC=clang \
          ARCH=$ARCH \
          SUBARCH=$SUBARCH \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi- \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CONFIG_NO_ERROR_ON_MISMATCH=y \
          2>&1 | tee build.log

    - name: Check build result
      run: |
        if [ -f arch/arm64/boot/Image ]; then
          echo "✅ Kernel built successfully!"
          ls -la arch/arm64/boot/
        else
          echo "❌ Kernel build failed!"
          echo "Last 50 lines of build log:"
          tail -50 build.log
          exit 1
        fi

    - name: Prepare kernel image
      run: |
        mkdir -p output
        
        # Copy kernel image
        cp arch/arm64/boot/Image output/
        
        # Create kernel zip name with timestamp
        TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
        KERNEL_ZIP="$KERNEL_NAME-$DEVICE-$TIMESTAMP.zip"
        echo "KERNEL_ZIP=$KERNEL_ZIP" >> $GITHUB_ENV
        
        # Get kernel version
        KERNEL_VERSION=$(cat include/config/kernel.release 2>/dev/null || echo "unknown")
        echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
        
        # Create info file
        cat > output/build_info.txt << EOF
        Kernel: $KERNEL_NAME
        Device: $DEVICE
        Version: $KERNEL_VERSION
        KernelSU: ${{ inputs.kernelsu_tag }}
        SUSFS: ${{ inputs.susfs_repo }}
        Built: $(date)
        Builder: $BUILD_USER
        EOF

    - name: Create flashable zip
      run: |
        cd output
        
        # Create AnyKernel3 structure
        mkdir -p anykernel3
        cd anykernel3
        
        # Download AnyKernel3
        wget -q https://github.com/osm0sis/AnyKernel3/archive/refs/heads/master.zip
        unzip -q master.zip
        cp -r AnyKernel3-master/* .
        rm -rf AnyKernel3-master master.zip
        
        # Configure AnyKernel3 for Beyond2LTE
        cat > anykernel.sh << 'EOF'
        # AnyKernel3 Ramdisk Mod Script
        # osm0sis @ xda-developers
        
        ## AnyKernel setup
        # begin properties
        properties() { '
        kernel.string=ExtremeKRNL-Nexus-KernelSU
        do.devicecheck=1
        do.modules=0
        do.systemless=1
        do.cleanup=1
        do.cleanuponabort=0
        device.name1=beyond2lte
        device.name2=beyond2
        device.name3=SM-G975F
        device.name4=
        device.name5=
        supported.versions=9-14
        supported.patchlevels=
        '; } # end properties
        
        # shell variables
        block=/dev/block/platform/13d60000.ufs/by-name/boot;
        is_slot_device=0;
        ramdisk_compression=auto;
        
        ## AnyKernel methods (DO NOT CHANGE)
        # import patching functions/variables - see for reference
        . tools/ak3-core.sh;
        
        ## AnyKernel file attributes
        # set permissions/ownership for included ramdisk files
        set_perm_recursive 0 0 755 644 $ramdisk/*;
        set_perm_recursive 0 0 750 750 $ramdisk/init* $ramdisk/sbin;
        
        ## AnyKernel boot install
        dump_boot;
        write_boot;
        EOF
        
        # Copy kernel image
        cp ../Image .
        
        # Create zip
        zip -r ../$KERNEL_ZIP * -x "*.git*" "*.md" "*.txt"
        
        cd ..
        echo "Flashable zip created: $KERNEL_ZIP"
        ls -la $KERNEL_ZIP

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_ZIP }}
        path: |
          output/${{ env.KERNEL_ZIP }}
          output/build_info.txt
          build.log

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: ${{ env.KERNEL_VERSION }}-${{ github.run_number }}
        name: ${{ env.KERNEL_NAME }} - ${{ env.KERNEL_VERSION }}
        body: |
          ## KernelSU Build for Beyond2LTE
          
          **Device:** ${{ env.DEVICE }}
          **Kernel Version:** ${{ env.KERNEL_VERSION }}
          **KernelSU:** ${{ inputs.kernelsu_tag }}
          **SUSFS:** ${{ inputs.susfs_repo }}
          **Built:** $(date)
          
          ### Installation
          1. Boot into custom TWRP (Extreme's version)
          2. Flash the kernel zip
          3. Reboot
          4. Install KernelSU manager app
          
          ### Features
          - KernelSU integrated
          - SUSFS support
          - Optimized for Extreme ROM NEXUS
          - Self-healing build system
          
        files: |
          output/${{ env.KERNEL_ZIP }}
          output/build_info.txt
        token: ${{ secrets.GH_PUSH_TOKEN }}

    - name: Build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Status:** ✅ Success" >> $GITHUB_STEP_SUMMARY
        echo "- **Kernel:** $KERNEL_NAME" >> $GITHUB_STEP_SUMMARY
        echo "- **Device:** $DEVICE" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** $KERNEL_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "- **KernelSU:** ${{ inputs.kernelsu_tag }}" >> $GITHUB_STEP_SUMMARY
        echo "- **SUSFS:** ${{ inputs.susfs_repo }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Output:** $KERNEL_ZIP" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ccache stats" >> $GITHUB_STEP_SUMMARY
        ccache --show-stats >> $GITHUB_STEP_SUMMARY
