name: Import Latest Release from Upstream

on:
  workflow_dispatch:

jobs:
  import-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Download and extract latest release
        run: |
          curl -L -o latest.zip https://github.com/ExtremeXT/M62-backport/archive/refs/tags/latest.zip
          unzip latest.zip
          rm latest.zip
          shopt -s extglob
          mv M62-backport-*/*!(".github") . || true

      - name: Commit only if there are changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet && echo "No changes to commit." || git commit -m "Import latest release from ExtremeXT/M62-backport"

      - name: Push using raw PAT (insecure method)
        run: |
          git remote set-url origin https://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@github.com/iHagoss/KERN.git
          git push origin HEAD:main
