name: Import Latest Release from Upstream

on:
  workflow_dispatch:

jobs:
  import-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Download and extract latest release
        run: |
          curl -L -o latest.zip https://github.com/ExtremeXT/M62-backport/archive/refs/tags/latest.zip
          unzip latest.zip
          rm latest.zip
          shopt -s extglob
          mv M62-backport-*/*!(".github") . || true

      - name: Configure Git identity
        run: |
          git config --global user.name "iHagoss"
          git config --global user.email "178996594+iHagoss@users.noreply.github.com"

      - name: Commit only if there are changes
        run: |
          git add .
          git diff --cached --quiet && echo "No changes to commit." || git commit -m "Import latest release from ExtremeXT/M62-backport"

      - name: Pull latest changes before push
        env:
          TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/iHagoss/KERN.git
          git config --global credential.helper ""
          git pull origin main --rebase

      - name: Push using secure token
        env:
          TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git push origin HEAD:main

      - name: Debug Git Setup (optional)
        run: |
          git remote -v
          git config --get user.name
          git config --get user.email
